import Link from "next/link";
import { BuildInvitation } from "../lab-interactions";
export const metadata={title:"Capabilities — Veya Labs",description:"Expressive design, precise engineering and connected business systems."};
const services=[
["design","01","Design","Make the right kind of noise.","From the first impression to the smallest interaction, we give your business a visual language of its own.",["Creative direction & brand expression","User journeys & interface design","Responsive design systems","Motion & interactive experiences"]],
["technology","02","Development","Beautiful is only the beginning.","The experience needs to hold up when people actually use it. We build the structure, speed and functionality behind the surface.",["Custom website development","Content management systems","Performance & accessibility","Forms, accounts & custom features"]],
["commerce","03","Commerce","Turn interest into intent.","A considered storefront. A clear product story. A smoother route from the first look to the final checkout.",["Shopify storefronts","Collections & product templates","Payment gateway integration","Shopping & checkout journeys"]],
["intelligence","04","Intelligence","Put repetition on autopilot.","Help people find answers and help your team act on the right information. Useful intelligence, connected to real work.",["Knowledge-grounded assistants","Lead qualification & summaries","CRM handoffs","Workflow automation"]],
["search","05","Discovery","Be there when it matters.","Give search engines and answer systems a clear understanding of your business, your expertise and your content.",["Technical SEO foundations","Content hierarchy & metadata","Structured data","Indexing & measurement setup"]],
["connections","06","Connections","Make every system a teammate.","Your website should fit into the way you work. We connect the tools, channels and processes around it.",["Booking & appointments","CRM & email platforms","WhatsApp & enquiries","Analytics & reporting integrations"]]
];
export default function Services(){return <main className="vl-main"><section className="vl-page-head vl-services-head"><span className="vl-label">THE CAPABILITIES / 01—06</span><h1>Many disciplines.<br/><em>One unfair advantage.</em></h1><p>Bring us the challenge. We’ll connect the right mix of creative thinking and technical depth.</p><nav className="vl-service-jump" aria-label="Capabilities">{services.map(([id,num,title])=><a href={'#'+id} key={id as string}><span>{num}</span>{title}</a>)}</nav></section><section className="vl-services-list">{services.map(([id,num,title,lead,copy,items])=><article className={'vl-service vl-service-'+num} id={id as string} key={id as string}><div className="vl-service-index"><span>{num}</span><small>{title}</small></div><div className="vl-service-copy"><h2>{lead as string}</h2><p>{copy as string}</p><details><summary>Inside this capability <span>+</span></summary><ul>{(items as string[]).map(x=><li key={x}>{x}</li>)}</ul></details><Link className="vl-link" href="/build">Add it to your ambition <span>↗</span></Link></div></article>)}</section><BuildInvitation/></main>}
