import type { Metadata } from "next";

export const metadata: Metadata = { title: "Services — STUDIO/AE", description: "Web design, development, ecommerce, search, AI and practical integrations for UAE businesses." };

const services=[
  ["01","design","Web design","Give the business a visual system people remember—and an interface they understand immediately.","Attention → understanding → action",["Art direction","UX / UI","Responsive systems","Conversion journeys"]],
  ["02","development","Web development","Turn the approved direction into a fast, accessible website that is straightforward to maintain.","Interface → engineering → launch",["Modern frontend","CMS","Custom functionality","Performance"]],
  ["03","search","SEO + AEO","Make the business easier for search engines and answer systems to interpret without promising impossible rankings.","Structure → clarity → discovery",["Technical foundations","On-page SEO","Structured content","Search indexing"]],
  ["04","automation","AI + automation","Use approved business knowledge to answer questions, qualify enquiries and remove repetitive handoffs.","Enquiry → context → next action",["Website assistants","Lead qualification","Enquiry summaries","Workflow automation"]],
  ["05","commerce","Ecommerce","Create a clearer path from product discovery to purchase, usually with Shopify handling the operational core.","Browse → choose → buy",["Shopify storefronts","Products + collections","Payments","Conversion optimisation"]],
  ["06","integrations","Integrations","Connect the website to the systems already running the business instead of creating another isolated tool.","Website → system → team",["CRM","Booking","WhatsApp","Analytics + newsletters"]],
];

export default function ServicesPage(){return <main className="page-shell services-page"><section className="services-masthead"><div><small>CAPABILITIES / 01—06</small><h1>Choose the problem.<br/>Then choose the technology.</h1></div><div className="services-masthead-copy"><p>Websites are rarely just a design job or a development job. We connect the disciplines needed to make the finished thing useful.</p><a href="/build">Build a scope <span>↗</span></a></div></section><section className="service-directory section-pad"><aside><small>CAPABILITY INDEX</small><nav aria-label="Service sections">{services.map(([n,id,title])=><a key={id as string} href={`#${id}`}><span>{n as string}</span>{title as string}</a>)}</nav><p>Pick one capability or combine several. The estimator prices the exact mix.</p></aside><div className="service-chapters">{services.map(([n,id,title,copy,flow,items])=><article id={id as string} key={id as string}><header><small>{n as string}</small><span>{flow as string}</span></header><h2>{title as string}</h2><p>{copy as string}</p><ul>{(items as string[]).map(x=><li key={x}>{x}<span>↗</span></li>)}</ul></article>)}</div></section><section className="service-stack"><div><small>THE RULE</small><h2>The stack follows the job.</h2></div><div className="stack-paths"><article><span>01</span><strong>Focused company site</strong><p>Modern custom frontend with a lean editing setup where needed.</p></article><article><span>02</span><strong>Content-led business</strong><p>A structured CMS for pages, services, people, articles and FAQs.</p></article><article><span>03</span><strong>Store or platform</strong><p>Shopify or a tailored application stack when the workflow genuinely requires it.</p></article></div><a href="/contact">Discuss the right approach <span>↗</span></a></section></main>}
