"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";

type Config = { website:string; pages:string; design:string; features:string[]; content?:string[]; business?:string[]; ai?:string[]; estimate:number; recommendation:string; nearestPackage?:string; origin?:"package"|"custom"; startedFrom?:string|null; journeyDecision?:string; advisorDecision?:string; added?:string[]; removed?:string[]; changed?:string[]; fitActions?:string[]; automaticLogic?:string[] };
const formatAED=(value:number)=>new Intl.NumberFormat("en-AE").format(value);

export default function ContactForm(){
  const [config,setConfig]=useState<Config|null>(null);
  const [need,setNeed]=useState("New website");
  const [budget,setBudget]=useState("AED 2,500–5,000");
  const [status,setStatus]=useState<"idle"|"sending"|"sent"|"error">("idle");
  const [error,setError]=useState("");
  useEffect(()=>{const frame=requestAnimationFrame(()=>{try{const saved=sessionStorage.getItem("studioConfig");if(saved){const next=JSON.parse(saved) as Config;if(!Array.isArray(next.features)||!next.features.every(item=>typeof item==="string")||!Number.isFinite(next.estimate)||typeof next.website!=="string")return;setConfig(next);setNeed(next.website==="Ecommerce"?"Ecommerce":next.features.some(feature=>feature.startsWith("AI "))?"AI / automation":"New website");setBudget(next.estimate<2500?"AED 999–2,499":next.estimate<=5000?"AED 2,500–5,000":next.estimate<=10000?"AED 5,000–10,000":"AED 10,000+")}}catch{}});return()=>cancelAnimationFrame(frame)},[]);
  const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setStatus("sending");setError("");const form=e.currentTarget;const data=Object.fromEntries(new FormData(form));
    try{const response=await fetch("/api/enquiry",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...data,configuration:config})});const result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error||"Unable to submit your enquiry.");try{sessionStorage.removeItem("studioConfig");sessionStorage.removeItem("studioBuilderDraft");}catch{}setStatus("sent");form.reset()}catch(err){setError(err instanceof Error?err.message:"Unable to submit your enquiry.");setStatus("error")}
  };
  if(status==="sent")return <div className="success-state" role="status"><span>✓</span><small>ENQUIRY SENT</small><h3>Project received.</h3><p>Thank you. We’ll review the requirements and come back with a clear next step.</p><Link href="/">Return home ↗</Link></div>;
  return <form className="contact-form" onSubmit={submit}>{config&&<div className="selected-config selected-config-smart"><div><small>{config.startedFrom?`STARTED FROM ${config.startedFrom}`:"CUSTOM-BUILT SCOPE"}</small><strong>{config.website} · {config.pages} pages</strong><span>{config.design} · Nearest package: {config.nearestPackage||config.recommendation}</span><details><summary>View selected scope</summary><div className="contact-scope-list"><p>{config.features.length?config.features.join(" · "):"No optional features selected"}</p>{config.added&&config.added.length>0&&<p><b>Added:</b> {config.added.join(", ")}</p>}{config.removed&&config.removed.length>0&&<p><b>Removed:</b> {config.removed.join(", ")}</p>}{config.changed&&config.changed.length>0&&<p><b>Changed:</b> {config.changed.join(", ")}</p>}</div></details><Link href="/build">Edit this scope ↗</Link></div><b>AED {formatAED(config.estimate)}<small>indicative estimate</small></b></div>}<input className="form-trap" name="website_url" tabIndex={-1} autoComplete="off" aria-hidden="true"/><div className="form-row"><label>Name<input required name="name" maxLength={80} autoComplete="name" placeholder="Your name"/></label><label>Company<input name="company" maxLength={120} autoComplete="organization" placeholder="Company name"/></label></div><div className="form-row"><label>Email<input required name="email" type="email" maxLength={180} autoComplete="email" placeholder="you@company.com"/></label><label>Phone / WhatsApp<input name="phone" maxLength={40} autoComplete="tel" placeholder="+971"/></label></div><div className="form-row"><label>What do you need?<select name="need" value={need} onChange={event=>setNeed(event.target.value)}><option>New website</option><option>Website redesign</option><option>Ecommerce</option><option>AI / automation</option><option>Something else</option></select></label><label>Approximate budget<select name="budget" value={budget} onChange={event=>setBudget(event.target.value)}><option>AED 999–2,499</option><option>AED 2,500–5,000</option><option>AED 5,000–10,000</option><option>AED 10,000+</option><option>Not sure yet</option></select></label></div><label>Target launch date<input name="launch" maxLength={100} placeholder="When would you like to launch?"/></label><label>Tell us about the project<textarea required name="message" minLength={20} maxLength={3000} rows={5} placeholder="What should the website help your business do?"/></label>{error&&<div className="form-error" role="alert">{error}</div>}<button className="submit-project" disabled={status==="sending"}>{status==="sending"?"Submitting…":"Submit project enquiry"}<span>↗</span></button><p>We’ll confirm when your enquiry has been sent. If delivery is unavailable, your saved estimate stays in this browser tab.</p></form>
}
