import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {DRACOLoader} from 'three/addons/loaders/DRACOLoader.js';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {places,type PlaceId} from './campus-data';
import {routeAcrossCampus,walkable,type Point} from './campus-navigation';
export type CampusControl={focus:(id:PlaceId|null)=>void;home:()=>void;zoom:(delta:number)=>void;night:(value:boolean)=>void;dispose:()=>void};
type Callbacks={ready:()=>void;lost:()=>void;visit:(id:PlaceId)=>void;markers:(positions:{id:PlaceId;x:number;y:number;visible:boolean}[])=>void};
export async function mountCampus(host:HTMLElement,callbacks:Callbacks):Promise<CampusControl>{
 const renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setClearColor(0,0);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.domElement.setAttribute('aria-hidden','true');host.appendChild(renderer.domElement);
 const scene=new THREE.Scene(),camera=new THREE.OrthographicCamera(-12,12,9,-9,.1,120);camera.position.set(17,23,23);camera.lookAt(0,.4,0);
 const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,.4,0);controls.enableDamping=true;controls.dampingFactor=.08;controls.enablePan=false;controls.enableZoom=false;controls.minPolarAngle=.35;controls.maxPolarAngle=1.15;controls.mouseButtons={LEFT:THREE.MOUSE.ROTATE,MIDDLE:THREE.MOUSE.DOLLY,RIGHT:THREE.MOUSE.ROTATE};controls.touches={ONE:THREE.TOUCH.ROTATE,TWO:THREE.TOUCH.DOLLY_PAN};
 const sky=new THREE.HemisphereLight(0xf0f5ff,0x68765d,3);scene.add(sky);const sun=new THREE.DirectionalLight(0xfff1d9,4.2);sun.position.set(-7,16,8);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-12,right:12,top:12,bottom:-12,near:1,far:50});sun.shadow.normalBias=.04;scene.add(sun);const fill=new THREE.DirectionalLight(0xc5d8ff,1.2);fill.position.set(5,8,-5);scene.add(fill);
 const decoder=new DRACOLoader().setDecoderPath('/models/draco/').setDecoderConfig({type:'wasm'}).setWorkerLimit(1);
 let model:THREE.Group|undefined,explorer:THREE.Object3D|undefined,disposed=false,lost=false,visible=true,night=false,zoom=1,targetZoom=1,walking=false,jump=0,velocity=0,lastTime=0;const destination=new THREE.Vector3(0,.075,2),focusPoint=new THREE.Vector3(0,.4,0),keys=new Set<string>(),pointer=new THREE.Vector2(),raycaster=new THREE.Raycaster();const reduced=matchMedia('(prefers-reduced-motion: reduce)');
 // Walking is constrained to the clear promenades. Clicked destinations approach the front of each pavilion.
 let waypoints:Point[]=[];
 const travel=(x:number,z:number)=>{if(!explorer)return;waypoints=routeAcrossCampus(explorer.position,{x,z});if(reduced.matches&&waypoints.length){const end=waypoints[waypoints.length-1];explorer.position.set(end.x,.075,end.z);destination.copy(explorer.position);waypoints=[]}};
 const stops:Record<PlaceId,[number,number]>={services:[-4.6,-.82],build:[4.55,-.6],pricing:[3.8,1.15],about:[-3.2,1.35],process:[0,-3.6],contact:[0,3.5]};
 const markerPositions=()=>{const r=host.getBoundingClientRect();callbacks.markers(places.map(p=>{const v=new THREE.Vector3(p.x,p.height,p.z).project(camera);return {id:p.id,x:(v.x*.5+.5)*r.width,y:(-.5*v.y+.5)*r.height,visible:v.z>-1&&v.z<1&&Math.abs(v.x)<.95&&Math.abs(v.y)<.95}}))};
 const render=(time=0)=>{if(disposed||lost)return;const dt=lastTime?Math.min((time-lastTime)/1000,.04):.016;lastTime=time;
  if(explorer){let dx=0,dz=0;if(keys.has('arrowleft')||keys.has('a'))dx-=1;if(keys.has('arrowright')||keys.has('d'))dx+=1;if(keys.has('arrowup')||keys.has('w'))dz-=1;if(keys.has('arrowdown')||keys.has('s'))dz+=1;
   if(dx||dz){const right=new THREE.Vector3().setFromMatrixColumn(camera.matrix,0);right.y=0;right.normalize();const forward=new THREE.Vector3().crossVectors(right,new THREE.Vector3(0,1,0)).normalize();const dir=right.multiplyScalar(dx).add(forward.multiplyScalar(dz)).normalize();waypoints=[];const next=explorer.position.clone().addScaledVector(dir,.2);if(walkable(next))destination.copy(next);else destination.copy(explorer.position);walking=true;}
   if(!dx&&!dz&&waypoints.length){const next=waypoints[0];destination.set(next.x,.075,next.z);if(Math.hypot(explorer.position.x-next.x,explorer.position.z-next.z)<.07)waypoints.shift()}
   const delta=new THREE.Vector3(destination.x-explorer.position.x,0,destination.z-explorer.position.z);if(delta.length()>.05){walking=true;const stride=Math.min(delta.length(),dt*3.2);delta.normalize();explorer.position.addScaledVector(delta,stride);explorer.rotation.y=Math.atan2(delta.x,delta.z)+Math.PI}else walking=false;
   if(jump>0||velocity>0){velocity-=dt*9;jump=Math.max(0,jump+velocity*dt);if(jump===0)velocity=0}explorer.position.y=.075+jump+(!reduced.matches&&walking?Math.abs(Math.sin(time*.013))*.07:0);
  }
  if(!reduced.matches){controls.target.lerp(focusPoint,.045);zoom=THREE.MathUtils.lerp(zoom,targetZoom,.06)}else{controls.target.copy(focusPoint);zoom=targetZoom}camera.zoom=zoom;camera.updateProjectionMatrix();controls.update();renderer.render(scene,camera);markerPositions();
 };
 const loop=()=>{lastTime=0;renderer.setAnimationLoop(!disposed&&!lost&&visible&&!document.hidden?render:null);if(visible)render()};
 const resize=()=>{const r=host.getBoundingClientRect();if(!r.width||!r.height)return;const aspect=r.width/r.height;const height=aspect<1?24/aspect:19;camera.left=-height*aspect/2;camera.right=height*aspect/2;camera.top=height/2;camera.bottom=-height/2;camera.updateProjectionMatrix();renderer.setSize(r.width,r.height);render()};
 const focus=(id:PlaceId|null)=>{const place=places.find(p=>p.id===id);focusPoint.set(place?place.x*.18:0,.4,place?place.z*.18:0);targetZoom=place?1.04:1;if(id){const stop=stops[id];travel(stop[0],stop[1])}render()};
 const hit=(e:PointerEvent)=>{const r=host.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);raycaster.setFromCamera(pointer,camera);return model?raycaster.intersectObject(model,true):[]};
 let press={x:0,y:0};const down=(e:PointerEvent)=>{press={x:e.clientX,y:e.clientY};host.focus({preventScroll:true})};const up=(e:PointerEvent)=>{if(Math.hypot(e.clientX-press.x,e.clientY-press.y)>6)return;const hits=hit(e);const station=hits.map(h=>h.object.name.split('__')[0]).find(name=>places.some(p=>p.id===name)) as PlaceId|undefined;if(station){focus(station);callbacks.visit(station);return}const ground=hits.find(h=>h.object.name.startsWith('CAMPUS__'));if(ground&&explorer){travel(ground.point.x,ground.point.z)}};
 const keydown=(e:KeyboardEvent)=>{const k=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright',' '].includes(k)){e.preventDefault();keys.add(k);if(k===' '&&jump===0)velocity=3.5}if(k==='enter'&&explorer){const near=places.map(p=>({p,d:Math.hypot(explorer!.position.x-stops[p.id][0],explorer!.position.z-stops[p.id][1])})).sort((a,b)=>a.d-b.d)[0];if(near.d<2){callbacks.visit(near.p.id);focus(near.p.id)}}};const keyup=(e:KeyboardEvent)=>keys.delete(e.key.toLowerCase());const blur=()=>keys.clear();const contextLost=(e:Event)=>{e.preventDefault();lost=true;renderer.setAnimationLoop(null);callbacks.lost()};
 const observer=new ResizeObserver(resize);observer.observe(host);const intersection=new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;loop()});intersection.observe(host);host.addEventListener('pointerdown',down);host.addEventListener('pointerup',up);host.addEventListener('keydown',keydown);host.addEventListener('keyup',keyup);host.addEventListener('blur',blur);window.addEventListener('blur',blur);document.addEventListener('visibilitychange',loop);renderer.domElement.addEventListener('webglcontextlost',contextLost);
 const dispose=()=>{disposed=true;renderer.setAnimationLoop(null);observer.disconnect();intersection.disconnect();controls.dispose();host.removeEventListener('pointerdown',down);host.removeEventListener('pointerup',up);host.removeEventListener('keydown',keydown);host.removeEventListener('keyup',keyup);host.removeEventListener('blur',blur);window.removeEventListener('blur',blur);document.removeEventListener('visibilitychange',loop);renderer.domElement.removeEventListener('webglcontextlost',contextLost);scene.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();for(const m of Array.isArray(o.material)?o.material:[o.material])m.dispose()}});decoder.dispose();renderer.dispose();renderer.domElement.remove()};
 try{const response=await fetch('/models/veya-campus.glb');if(!response.ok)throw new Error('Campus unavailable');model=(await new GLTFLoader().setDRACOLoader(decoder).parseAsync(await response.arrayBuffer(),'/models/')).scene;model.traverse(o=>{if(o instanceof THREE.Mesh){o.castShadow=true;o.receiveShadow=true}});explorer=model.getObjectByName('EXPLORER');if(explorer)explorer.position.set(0,.075,2);scene.add(model);resize();callbacks.ready();loop()}catch(error){dispose();throw error}
 return {focus,home:()=>{focus(null);camera.position.set(17,23,23);controls.target.set(0,.4,0);targetZoom=1;if(explorer)explorer.position.set(0,.075,2);destination.set(0,.075,2);waypoints=[];render()},zoom:(d)=>{targetZoom=THREE.MathUtils.clamp(targetZoom+d,.75,1.65);render()},night:(value)=>{night=value;sky.intensity=night?1.4:3;sky.color.set(night?0x879cd2:0xf0f5ff);sun.intensity=night?1.4:4.2;sun.color.set(night?0xa9b8ff:0xfff1d9);fill.intensity=night?2:1.2;render()},dispose};
}
