"use client";
import { useEffect,useRef,useState } from "react";
import Image from "next/image";
import Link from "next/link";
import type { SculptureControl } from "./sculpture-scene";
const layers=[{name:"Design",title:"Feel something.",copy:"An identity with presence. A journey with purpose. Every detail working toward the same impression.",tags:["Art direction","UX + UI","Motion"],href:"/services#design"},{name:"Technology",title:"Make it work.",copy:"Behind the experience: fast pages, structured content and connected systems that do the heavy lifting.",tags:["Development","CMS","Integrations"],href:"/services#technology"},{name:"Intelligence",title:"Go further.",copy:"Turn incoming interest into useful context. Connect enquiries, knowledge and workflows around your team.",tags:["AI assistants","CRM","Automation"],href:"/services#intelligence"}];
export function LabSculpture({compact=false}:{compact?:boolean}){
 const host=useRef<HTMLDivElement>(null);const control=useRef<SculptureControl|null>(null);const [ready,setReady]=useState(false);const [expanded,setExpanded]=useState(false);const [finish,setFinish]=useState(0);const [turn,setTurn]=useState(0);
 useEffect(()=>{let cancelled=false;let instance:SculptureControl|null=null;const el=host.current;if(!el)return;import('./sculpture-scene').then(m=>m.mountSculpture(el,r=>{if(!cancelled)setReady(r)})).then(x=>{instance=x;if(cancelled)x.dispose();else control.current=x}).catch(()=>{if(!cancelled)setReady(false)});return()=>{cancelled=true;control.current=null;instance?.dispose()}},[]);
 useEffect(()=>{control.current?.update(expanded,finish,turn)},[expanded,finish,turn,ready]);
 return <div className={`vl-sculpture ${ready?'is-ready':''} ${compact?'is-compact':''}`}><div className="vl-sculpture-stage"><Image src="/models/veya-core.webp" alt="Veya's sculptural chrome V, built from separate precision layers" width={1200} height={1200} priority={!compact} unoptimized className="vl-sculpture-poster"/><div ref={host} className="vl-sculpture-canvas"/></div><div className="vl-sculpture-caption"><span className="vl-label">VEYA CORE / 01</span><span>{ready?'Drag to rotate':'Design. Technology. Intelligence.'}</span></div><div className="vl-sculpture-controls"><button type="button" aria-pressed={expanded} onClick={()=>setExpanded(!expanded)}>{expanded?'Assemble':'Explore the layers'} <span>{expanded?'−':'+'}</span></button>{ready&&<button type="button" aria-label="Rotate sculpture 45 degrees" onClick={()=>setTurn(turn+Math.PI/4)}>Turn ↻</button>}{ready&&<button type="button" aria-label="Change sculpture finish" onClick={()=>setFinish((finish+1)%3)}>Finish <i style={{background:['#dde1df','#deff00','#8b7bff'][finish]}}/></button>}</div>{expanded&&<p className="vl-layer-note">Design, technology and intelligence. Distinct disciplines, one connected experience.</p>}</div>
}
export function CapabilityExplorer(){const [active,setActive]=useState(0);const item=layers[active];return <section className="vl-explorer vl-pad"><div className="vl-explorer-heading"><span className="vl-label">02 / CONNECTED CAPABILITIES</span><h2>Good alone.<br/><em>Exceptional together.</em></h2></div><div className="vl-explorer-grid"><div className="vl-explorer-tabs" role="tablist" aria-label="Explore capabilities">{layers.map((l,i)=><button id={`cap-tab-${i}`} aria-controls={`cap-panel-${i}`} role="tab" aria-selected={active===i} tabIndex={active===i?0:-1} onKeyDown={e=>{if(['ArrowDown','ArrowRight','ArrowUp','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?2:(active+(e.key==='ArrowDown'||e.key==='ArrowRight'?1:2))%3;setActive(next);document.getElementById(`cap-tab-${next}`)?.focus()}}} onClick={()=>setActive(i)} key={l.name}><small>0{i+1}</small><span>{l.name}</span><b>↗</b></button>)}</div><div className={`vl-cap-panel cap-${active}`} id={`cap-panel-${active}`} role="tabpanel" aria-labelledby={`cap-tab-${active}`} key={active}><span className="vl-cap-number" aria-hidden="true">0{active+1}</span><div><h3>{item.title}</h3><p>{item.copy}</p><div className="vl-tags">{item.tags.map(t=><span key={t}>{t}</span>)}</div><Link className="vl-link" href={item.href}>Explore {item.name.toLowerCase()} <span>↗</span></Link></div></div></div></section>}
export function BuildInvitation(){return <section className="vl-build-invitation"><div><span className="vl-label">YOUR AMBITION. YOUR COMBINATION.</span><h2>What if<br/><em>starts here.</em></h2><p>Six decisions turn an idea into a scope. Explore the possibilities, see your estimate and make it yours.</p><Link className="vl-button vl-button-black" href="/build">Enter the estimator <span>↗</span></Link></div><div className="vl-build-price"><span className="vl-label">WEBSITES FROM</span><strong>999<sup>AED</sup></strong><Link href="/pricing">Four starting points. Endless potential. ↗</Link></div></section>}
