import Link from "next/link";
import { LabSculpture, CapabilityExplorer, BuildInvitation } from "./lab-interactions";
export default function Home(){return <main className="vl-main">
<section className="vl-hero"><div className="vl-hero-meta vl-label"><span>INDEPENDENT DIGITAL LAB / UAE</span><span>DESIGN × TECHNOLOGY × AMBITION</span></div><h1>Make yourself<br/><em>impossible</em><br/>to ignore<span className="vl-period">.</span></h1><div className="vl-hero-art"><LabSculpture/></div><div className="vl-hero-bottom"><p>We turn ambitious businesses into unforgettable digital experiences. Designed to move people. Built to move business.</p><Link className="vl-button" href="/build">Build your next chapter <span>↗</span></Link><span className="vl-label vl-scroll">SCROLL TO DISCOVER ↓</span></div></section>
<div className="vl-marquee" aria-label="Design, development, commerce and intelligence"><div aria-hidden="true">DESIGN WITH INTENT <b>✳</b> BUILD WITH PRECISION <b>✳</b> THINK BEYOND THE PAGE <b>✳</b> DESIGN WITH INTENT <b>✳</b> BUILD WITH PRECISION <b>✳</b> THINK BEYOND THE PAGE <b>✳</b></div></div>
<section className="vl-intro vl-pad"><span className="vl-label">01 / THE BIGGER PICTURE</span><h2>Your website isn’t<br/>the destination.<br/><span>It’s the beginning.</span></h2><div className="vl-intro-bottom"><span className="vl-cross" aria-hidden="true">✳</span><p>A first impression. A booking. A sale. A conversation that changes everything. We connect expressive design with the systems that make those moments happen.</p><Link href="/about" className="vl-link">Meet the lab <span>↗</span></Link></div></section>
<CapabilityExplorer/>
<section className="vl-statement vl-pad"><span className="vl-label">03 / SMALL TEAM. FULL PICTURE.</span><h2>Less agency.<br/><em>More chemistry.</em></h2><div className="vl-statement-grid">{[["Direct by design","Work with the people making the decisions and building the experience."],["Nothing in a black box","Know what you’re getting, what it costs and what happens next."],["Made to keep moving","A website you can own, update and build on as the business grows."]].map(([t,p],i)=><article key={t}><span>0{i+1}</span><h3>{t}</h3><p>{p}</p></article>)}</div><Link className="vl-link" href="/process">Inside our process <span>↗</span></Link></section>
<BuildInvitation/></main>}
