import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { DRACOLoader } from 'three/addons/loaders/DRACOLoader.js';
import { RoomEnvironment } from 'three/addons/environments/RoomEnvironment.js';
export type SculptureControl={update:(expanded:boolean,finish:number,turn:number)=>void;dispose:()=>void};
export async function mountSculpture(host:HTMLElement,onReady:(value:boolean)=>void):Promise<SculptureControl>{
 const renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setClearColor(0,0);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;renderer.domElement.setAttribute('aria-hidden','true');host.appendChild(renderer.domElement);
 const scene=new THREE.Scene();const camera=new THREE.OrthographicCamera(-3,3,3,-3,.1,50);camera.position.set(5,4,10);camera.lookAt(0,0,0);
 const pmrem=new THREE.PMREMGenerator(renderer),room=new RoomEnvironment(),env=pmrem.fromScene(room,.02);scene.environment=env.texture;scene.environmentIntensity=2;room.dispose();pmrem.dispose();
 scene.add(new THREE.HemisphereLight(0xffffff,0x777788,2));for(const [pos,color,power] of [[[4,4,5],0xffffff,5],[[-4,2,-3],0xdeff55,4],[[0,-4,3],0xaabbff,3]] as [number[],number,number][]){const light=new THREE.DirectionalLight(color,power);light.position.set(...pos as [number,number,number]);scene.add(light)}
 const decoder=new DRACOLoader().setDecoderPath('/models/draco/').setDecoderConfig({type:'wasm'}).setWorkerLimit(1);const reduced=matchMedia('(prefers-reduced-motion: reduce)');let disposed=false,visible=true,lost=false,model:THREE.Group|undefined,expanded=false,finish=0,spread=0,angle=0,drag=false,lastX=0;const target=new THREE.Vector2(),parts:{obj:THREE.Object3D,z:number,index:number}[]=[];
 const paint=()=>{if(!model)return;model.traverse(o=>{if(o instanceof THREE.Mesh&&o.material instanceof THREE.MeshStandardMaterial&&o.material.name==='Polished titanium'){o.material.color.set(['#cbd1d5','#d7f537','#8e79eb'][finish]);o.material.roughness=finish===0?.19:.28}})};
 const render=(time=0)=>{if(disposed||lost)return;if(model){spread=reduced.matches?(expanded?1:0):THREE.MathUtils.lerp(spread,expanded?1:0,.055);parts.forEach(p=>p.obj.position.z=p.z-(p.index-3)*spread*.38);model.rotation.y=angle+(reduced.matches?0:Math.sin(time*.00022)*.065+target.x*.1);model.rotation.x=reduced.matches?0:target.y*.06;model.position.y=reduced.matches?0:Math.sin(time*.00065)*.045}renderer.render(scene,camera)};
 const loop=()=>{renderer.setAnimationLoop(!disposed&&!lost&&visible&&!document.hidden&&!reduced.matches?render:null);if(visible)render()};
 const resize=()=>{const r=host.getBoundingClientRect();if(!r.width||!r.height)return;const s=6.1;camera.left=-s*r.width/r.height/2;camera.right=-camera.left;camera.top=s/2;camera.bottom=-s/2;camera.updateProjectionMatrix();renderer.setSize(r.width,r.height);render()};
 const move=(e:PointerEvent)=>{if(drag){angle+=(e.clientX-lastX)*.008;lastX=e.clientX;render();return}if(e.pointerType==='touch')return;const r=host.getBoundingClientRect();target.set((e.clientX-r.left)/r.width-.5,(e.clientY-r.top)/r.height-.5)};
 const down=(e:PointerEvent)=>{if(e.pointerType==='touch')return;drag=true;lastX=e.clientX;host.setPointerCapture(e.pointerId);host.style.cursor='grabbing'};
 const up=()=>{drag=false;host.style.cursor='grab'};const contextLost=(e:Event)=>{e.preventDefault();lost=true;renderer.setAnimationLoop(null);onReady(false)};
 const observer=new ResizeObserver(resize);observer.observe(host);const intersection=new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;loop()});intersection.observe(host);host.addEventListener('pointermove',move);host.addEventListener('pointerdown',down);host.addEventListener('pointerup',up);host.addEventListener('pointercancel',up);document.addEventListener('visibilitychange',loop);reduced.addEventListener('change',loop);renderer.domElement.addEventListener('webglcontextlost',contextLost);
 const dispose=()=>{disposed=true;renderer.setAnimationLoop(null);observer.disconnect();intersection.disconnect();host.removeEventListener('pointermove',move);host.removeEventListener('pointerdown',down);host.removeEventListener('pointerup',up);host.removeEventListener('pointercancel',up);document.removeEventListener('visibilitychange',loop);reduced.removeEventListener('change',loop);renderer.domElement.removeEventListener('webglcontextlost',contextLost);scene.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();for(const m of Array.isArray(o.material)?o.material:[o.material])m.dispose()}});env.dispose();decoder.dispose();renderer.dispose();renderer.domElement.remove()};
 try{const response=await fetch('/models/veya-core.glb');if(!response.ok)throw new Error('Model unavailable');const gltf=await new GLTFLoader().setDRACOLoader(decoder).parseAsync(await response.arrayBuffer(),'/models/');model=gltf.scene;model.traverse(o=>{if(/^LAYER_[0-6]$/.test(o.name))parts.push({obj:o,z:o.position.z,index:Number(o.name.slice(-1))})});scene.add(model);paint();resize();onReady(true);loop()}catch(e){dispose();throw e}
 return {update:(ex,f,turn)=>{expanded=ex;finish=f;angle=turn;paint();render()},dispose};
}
