"use client";
import {useState} from 'react';
const disciplines=[
 {title:'Design',icon:'01',intro:'A website that feels like you.',copy:'We shape the visual direction, structure and interactions around your business and its audience.',items:['Art direction & brand expression','Responsive interface design','User journeys','Motion & interactive experiences']},
 {title:'Development',icon:'02',intro:'The care beneath the surface.',copy:'We turn the approved direction into a website that works well, loads efficiently and gives your content a clear home.',items:['Custom frontend development','Content management systems','Responsive implementation','Performance & accessibility']},
 {title:'Commerce',icon:'03',intro:'A considered way to shop.',copy:'From product discovery to checkout, we connect the storefront experience with the tools you need to run it.',items:['Shopify storefronts','Products & collections','Payment integration','Shopping journeys']},
 {title:'Intelligence',icon:'04',intro:'A little less repetitive work.',copy:'Connect useful business knowledge with your website and help the team make sense of incoming enquiries.',items:['Website assistants','Lead qualification','Enquiry summaries','Workflow automation']},
 {title:'Discovery',icon:'05',intro:'Help the right people find you.',copy:'Give search engines and answer systems a clearer understanding of your business and its content.',items:['Technical SEO foundations','Content hierarchy & metadata','Structured data','Indexing & analytics']},
 {title:'Connections',icon:'06',intro:'Everything working together.',copy:'Make the website part of your working day by connecting it to the channels and systems around it.',items:['Booking & appointments','CRM & email tools','WhatsApp enquiries','Analytics integrations']},
];
export function StudioDirectory(){const [active,setActive]=useState(0);const d=disciplines[active];return <div className="room-directory"><div role="tablist" aria-label="Studio disciplines" className="room-tabs">{disciplines.map((item,i)=><button type="button" role="tab" id={'discipline-'+i} aria-controls={'discipline-panel-'+i} aria-selected={i===active} tabIndex={i===active?0:-1} key={item.title} onClick={()=>setActive(i)} onKeyDown={e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?5:(active+(e.key==='ArrowRight'?1:5))%6;setActive(next);document.getElementById('discipline-'+next)?.focus()}}}>{item.title}</button>)}</div><section className="room-discipline" role="tabpanel" id={'discipline-panel-'+active} aria-labelledby={'discipline-'+active} key={active}><small>{d.icon} / {d.title}</small><h2>{d.intro}</h2><p>{d.copy}</p><ul>{d.items.map(item=><li key={item}>{item}</li>)}</ul></section><a className="room-action" href="/build">Explore a scope for your business <span>↗</span></a></div>}
