"use client";
import {useEffect,useRef,useState,type ReactNode} from 'react';
import {usePathname,useRouter} from 'next/navigation';
import Link from 'next/link';
import Image from 'next/image';
import {places,type PlaceId} from './campus-data';
import type {CampusControl} from './campus-scene';

export function WorldShell({children}:{children:ReactNode}){
 const path=usePathname(),router=useRouter();const host=useRef<HTMLDivElement>(null),instance=useRef<CampusControl|null>(null),labels=useRef<Record<string,HTMLButtonElement|null>>({});const menu=useRef<HTMLDetailsElement>(null);const [ready,setReady]=useState(false),[failed,setFailed]=useState(false),[night,setNight]=useState(false),[help,setHelp]=useState(false);const place=places.find(p=>p.path===path);const home=path==='/',wide=path==='/build'||path==='/contact'||path==='/privacy';
 const routeRef=useRef(router);routeRef.current=router;
 useEffect(()=>{let ended=false,control:CampusControl|null=null;const el=host.current;if(!el)return;
  import('./campus-scene').then(m=>m.mountCampus(el,{ready:()=>{if(!ended)setReady(true)},lost:()=>{if(!ended){setReady(false);setFailed(true)}},visit:id=>routeRef.current.push('/'+id),markers:positions=>{for(const p of positions){const label=labels.current[p.id];if(label){label.style.transform=`translate(${p.x}px,${p.y}px) translate(-50%,-100%)`;label.style.visibility=p.visible?'visible':'hidden'}}}})).then(c=>{control=c;if(ended)c.dispose();else instance.current=c}).catch(()=>{if(!ended)setFailed(true)});
  return()=>{ended=true;instance.current=null;control?.dispose()};
 },[]);
 useEffect(()=>{instance.current?.focus(place?.id??null);if(menu.current)menu.current.open=false},[path,place?.id,ready]);
 useEffect(()=>{instance.current?.night(night)},[night,ready]);
 useEffect(()=>{const id=requestAnimationFrame(()=>setNight(document.documentElement.dataset.theme==='dark'));return()=>cancelAnimationFrame(id)},[]);
 const theme=()=>{const next=!night;setNight(next);document.documentElement.dataset.theme=next?'dark':'light';try{localStorage.setItem('veya-theme',next?'dark':'light')}catch{}};
 const visit=(id:PlaceId)=>{instance.current?.focus(id);router.push('/'+id)};
 return <div className={`world-shell ${home?'at-home':'has-panel'} ${wide?'wide-panel':''} ${night?'world-night':''} ${path==='/pricing'?'pricing-room':''}`}>
  <div className={`world-environment ${ready?'environment-ready':''}`} aria-label="Veya Labs campus"><Image className="world-poster" src="/models/veya-campus.webp" alt="A miniature Veya Labs campus with a design studio, workshop, package gallery and meeting courtyard" width={1600} height={1100} unoptimized priority/><div className="world-canvas" ref={host} tabIndex={0} role="region" aria-label="Interactive campus. Drag to look around. Click to walk. Use W A S D or arrow keys to move, Space to jump, Enter to visit a nearby building."/>{ready&&<div className="world-labels">{places.map(p=><button type="button" key={p.id} ref={el=>{labels.current[p.id]=el}} onClick={()=>visit(p.id)} className={place?.id===p.id?'current':''}><i style={{background:p.color}}/><span>{p.name}</span><b>↗</b></button>)}</div>}</div>
  <header className="world-header"><Link className="world-brand" href="/" onClick={()=>instance.current?.home()}>veya<span>labs</span></Link><span className="world-header-note">A small digital world, built around yours.</span><div className="world-header-actions"><details className="world-menu" ref={menu}><summary>Places <span>⌄</span></summary><nav aria-label="Main navigation">{places.map(p=><Link key={p.id} href={p.path} aria-current={path===p.path?'page':undefined}><i style={{background:p.color}}/><div>{p.name}<small>{p.label}</small></div><span>↗</span></Link>)}<Link href="/privacy">Privacy + terms</Link></nav></details><Link className="world-direct" href="/build">Estimate a project <span>↗</span></Link></div></header>
  <div id="main-content" tabIndex={-1} className={home?'world-welcome':'world-panel'} key={path}>{!home&&<div className="world-panel-bar"><div><span className="world-panel-dot" style={{background:place?.color??'#567ea8'}}/>{place?.name??'Veya Labs'}</div><Link href="/" aria-label="Close panel and return to campus">×</Link></div>}{children}</div>
  {home&&<div className="world-destinations" aria-label="Quick destinations">{places.map(p=><Link key={p.id} href={p.path}><span style={{background:p.color}}/>{p.label}</Link>)}</div>}
  <footer className="world-hud"><div className="world-location"><span>{home?'Veya campus':place?.name??'Veya Labs'}</span><small>{failed?'Map view · use Places to explore':ready?'Explore at your own pace':'Preparing the interactive campus…'}</small></div><div className="world-tools"><button type="button" onClick={()=>{instance.current?.home();if(!home)router.push('/')}} aria-label="Reset campus view">⌂ <span>Map</span></button><button type="button" disabled={!ready} onClick={()=>instance.current?.zoom(.15)} aria-label="Zoom in">+</button><button type="button" disabled={!ready} onClick={()=>instance.current?.zoom(-.15)} aria-label="Zoom out">−</button><button type="button" onClick={theme} aria-label={`Switch to ${night?'day':'evening'} view`}>{night?'☀':'☾'}</button><button type="button" onClick={()=>setHelp(!help)} aria-expanded={help} aria-controls="world-help">?</button></div></footer>
  {help&&<aside id="world-help" className="world-help"><header><strong>Around the campus</strong><button type="button" onClick={()=>setHelp(false)} aria-label="Close instructions">×</button></header><p>Click a building or its label to visit. Drag the map to look around.</p><dl><div><dt>Click the ground</dt><dd>Take a walk</dd></div><div><dt>W A S D / arrows</dt><dd>Move your explorer</dd></div><div><dt>Space</dt><dd>A little jump</dd></div><div><dt>Enter</dt><dd>Visit a nearby place</dd></div></dl><p>On a phone, use the place labels or the Places menu. All information is available without playing.</p></aside>}
 </div>
}
