import * as T from 'three';
import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';
export type FoldControl={pose:(n:number,instant?:boolean)=>void;headline:(s:string)=>void;dispose:()=>void};
export function mountFold(host:HTMLElement,opts:{clay:boolean;study:number;mobile:boolean;ready:()=>void;stats:(s:string)=>void}):FoldControl{
 const scene=new T.Scene();scene.background=new T.Color('#171b20');
 const renderer=new T.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;host.appendChild(renderer.domElement);
 const camera=new T.OrthographicCamera(-6,6,4,-4,.1,100);camera.position.set(opts.mobile?0:7,opts.mobile?3:5,14);camera.lookAt(0,1.6,0);
 const porcelain=new T.MeshStandardMaterial({color:opts.clay?'#aaa9a5':'#e9e6de',roughness:.32,metalness:.08});const metal=new T.MeshStandardMaterial({color:'#8c9298',metalness:.8,roughness:.27});const cobalt=new T.MeshStandardMaterial({color:'#365cf5',metalness:.3,roughness:.3});const graphite=new T.MeshStandardMaterial({color:'#242b32',roughness:.55});
 function box(parent:T.Object3D,w:number,h:number,d:number,x:number,y:number,z:number,m:T.Material=porcelain,r=.055){const mesh=new T.Mesh(new RoundedBoxGeometry(w,h,d,3,r),m);mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);return mesh}
 function pin(parent:T.Object3D,x:number,y:number,z:number,h:number){const m=new T.Mesh(new T.CylinderGeometry(.075,.075,h,20),metal);m.position.set(x,y,z);m.castShadow=true;parent.add(m)}
 const root=new T.Group();scene.add(root);root.position.set(-.2,1.85,0);
 // One anchored chassis, with an asymmetric spine extending below the folio.
 box(root,3.55,2.7,.22,.25,0,-.12);box(root,.28,3.32,.38,-1.65,-.18,.02,cobalt);box(root,.78,.15,1.35,-1.55,-1.82,-.05,metal);box(root,2.65,.13,.8,.15,-1.66,-.13,graphite);
 const leaf=new T.Group();leaf.position.set(-1.65,0,.20);root.add(leaf);box(leaf,3.5,2.7,.13,1.8,0,0);box(leaf,.1,2.4,.16,3.51,0,0,cobalt,.03);
 for(const y of [-1.05,1.05]){pin(root,-1.65,y,.20,.36);box(leaf,.32,.17,.13,.13,y,0,metal,.025)}
 const wing=new T.Group();wing.position.set(1.95,0,-.06);root.add(wing);box(wing,1.12,2.3,.12,-.61,0,-.1);for(const y of [-.85,.85]){pin(root,1.95,y,-.06,.25);box(wing,.2,.12,.15,-.09,y,-.05,metal,.025)}
 const canvases:HTMLCanvasElement[]=[];const textures:T.CanvasTexture[]=[];
 function surface(parent:T.Object3D,w:number,h:number,x:number,y:number,z:number,back=false,kind='site'){
 const c=document.createElement('canvas');c.width=kind==='phone'?512:1536;c.height=kind==='phone'?1024:1080;canvases.push(c);const tex=new T.CanvasTexture(c);tex.colorSpace=T.SRGBColorSpace;tex.anisotropy=renderer.capabilities.getMaxAnisotropy();textures.push(tex);const mesh=new T.Mesh(new T.PlaneGeometry(w,h),new T.MeshBasicMaterial({map:tex,color:opts.clay?'#aaa9a5':'white'}));mesh.position.set(x,y,z);if(back)mesh.rotation.y=Math.PI;parent.add(mesh);return {c,tex,kind}}
 const displays=[surface(leaf,3.27,2.45,1.8,0,.071),surface(leaf,3.27,2.45,1.8,0,-.071,true),surface(root,3.2,2.35,.25,0,.001,false,'cms'),surface(wing,.95,2.06,-.61,0,-.165,true,'phone')];
 function draw(s:string){for(const {c,tex,kind} of displays){const g=c.getContext('2d')!;const w=c.width,h=c.height;g.fillStyle='#efeee7';g.fillRect(0,0,w,h);g.fillStyle='#233b33';g.font=`${kind==='phone'?27:30}px Arial`;g.fillText(kind==='cms'?'01 / CONTENT SOURCE':'SAHA   /   RETREAT',w*.07,h*.10);
 if(kind==='cms'){g.font='64px Georgia';g.fillText('One story.',100,285);g.fillText('Every screen.',100,365);g.fillStyle='#d5dbd3';g.fillRect(100,430,1336,300);g.fillStyle='#233b33';g.font='28px Arial';g.fillText('HERO HEADLINE',140,490);wrap(g,s,140,565,1200,60,48);g.font='28px Arial';g.fillText('Website  /  Mobile',100,865);g.fillText('LOCAL CONTENT DEMONSTRATION',100,970);
 }else{g.font=`${kind==='phone'?48:86}px Georgia`;wrap(g,s,w*.07,h*.24,w*.85,kind==='phone'?54:98,kind==='phone'?48:86);g.font=`${kind==='phone'?21:27}px Arial`;g.fillText('A slower kind of stay. Ras Al Khaimah.',w*.07,h*.44);g.fillStyle='#233b33';g.fillRect(w*.07,h*.49,w*.32,h*.065);g.fillStyle='#fff';g.fillText('Discover Saha ↗',w*.09,h*.534);
 // Original procedural editorial illustration: terraced desert architecture.
 g.fillStyle='#c6b69a';g.fillRect(w*.07,h*.60,w*.86,h*.31);g.fillStyle='#a19277';g.beginPath();g.moveTo(w*.07,h*.85);g.bezierCurveTo(w*.3,h*.6,w*.7,h*.95,w*.93,h*.68);g.lineTo(w*.93,h*.91);g.lineTo(w*.07,h*.91);g.fill();g.fillStyle='#e9dfca';g.fillRect(w*.34,h*.65,w*.40,h*.18);g.fillStyle='#d5c7af';g.fillRect(w*.39,h*.61,w*.30,h*.05);g.fillStyle='#464d3b';for(let i=0;i<5;i++)g.fillRect(w*(.37+i*.067),h*.69,w*.038,h*.14);g.fillStyle='#737b60';g.fillRect(w*.16,h*.80,w*.1,h*.03);g.font=`${kind==='phone'?16:23}px Arial`;g.fillStyle='#233b33';g.fillText('Fictional hospitality concept • UAE',w*.07,h*.965)}tex.needsUpdate=true}}
 function wrap(g:CanvasRenderingContext2D,s:string,x:number,y:number,width:number,line:number,size:number){g.font=`${size}px Georgia`;let row='';for(const word of s.split(' ')){if(g.measureText(row+word).width>width&&row){g.fillText(row,x,y);y+=line;row=''}row+=word+' '}g.fillText(row,x,y)}
 draw('Room to return to yourself.');
 const floor=box(scene,200,.15,200,0,-.18,0,new T.MeshStandardMaterial({color:'#252b31',roughness:.78}),.02);floor.receiveShadow=true;
 box(scene,18,.10,6,0,-.05,-1.3,new T.MeshStandardMaterial({color:'#30373d',roughness:.65}),.035);
 const key=new T.DirectionalLight('#fff1d9',4.5);key.position.set(-3,9,6);key.castShadow=true;key.shadow.mapSize.set(2048,2048);Object.assign(key.shadow.camera,{left:-9,right:9,top:8,bottom:-8});key.shadow.normalBias=.025;scene.add(key);scene.add(new T.HemisphereLight('#bfcfff','#20232a',1.9));const fill=new T.DirectionalLight('#b0c5ff',2);fill.position.set(5,4,-4);scene.add(fill);
 let value=0,target=0,raf=0,last=performance.now(),count=0,sum=0,max=0;const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
 function resize(){const w=host.clientWidth,h=host.clientHeight;renderer.setSize(w,h);const extent=opts.mobile?3.0:4.05;camera.left=-extent*w/h;camera.right=extent*w/h;camera.top=extent;camera.bottom=-extent;camera.updateProjectionMatrix()}
 const observer=new ResizeObserver(resize);observer.observe(host);resize();
 function pose(n:number,instant=false){target=n;if(instant||reduce)value=n}
 function render(now:number){const dt=Math.min((now-last)/1000,.1);last=now;value+=Math.sign(target-value)*Math.min(Math.abs(target-value),dt/1.2);const t=value*value*(3-2*value);leaf.rotation.y=-(opts.study===2?2.15:2.72)*t;wing.rotation.y=(opts.mobile?0:2.70)*t;wing.visible=!opts.mobile;root.rotation.z=opts.study===1?-.12:0;root.position.x=opts.mobile?-.2:1.1*t-.2;root.scale.setScalar(opts.mobile?.8:1);renderer.render(scene,camera);count++;sum+=dt;max=Math.max(max,dt);if(count%120===0){opts.stats(`${renderer.info.render.triangles.toLocaleString()} triangles · ${renderer.info.render.calls} draws · ${(count/sum).toFixed(0)} fps average · ${(max*1000).toFixed(0)} ms max interval`)}raf=requestAnimationFrame(render)}raf=requestAnimationFrame(render);opts.ready();
 return {pose,headline:draw,dispose(){cancelAnimationFrame(raf);observer.disconnect();scene.traverse(o=>{if(o instanceof T.Mesh){o.geometry.dispose();for(const m of Array.isArray(o.material)?o.material:[o.material])m.dispose()}});textures.forEach(t=>t.dispose());renderer.dispose();renderer.domElement.remove()}};
}
