import Link from "next/link";
export const metadata={title:"The Process — Veya Labs",description:"From the first what-if to a website you can launch, own and grow."};
const stages=[
["01","Get curious.","Discover","We ask about the business before we talk about the website. Who needs you? What should they do? Where is the friction?","A shared brief, agreed scope and a clear direction.","Your goals, useful references and the information customers need."],
["02","Make it tangible.","Design","We turn the brief into a visual direction and a journey you can explore. The big decisions happen while they are still easy to change.","An approved design system and key page layouts.","Focused feedback on the direction, content and user journey."],
["03","Bring it to life.","Build","Design becomes code. Content gets a home. Integrations connect. The details become the experience.","A working website with your agreed features connected.","Final content, required access and a review of the working build."],
["04","Make the entrance.","Launch","We check the practical details: mobile layouts, forms, links, performance, indexing and handover. Then it is time to go live.","A live release, handover and a defined support window.","Final approval and ownership of your platform accounts."],
["05","Keep evolving.","Grow","Your website should have somewhere to go next. Use real feedback to decide what deserves another iteration.","A clear view of the next useful improvements.","Business feedback and priorities as your needs change."]
];
export default function ProcessPage(){return <main className="vl-main"><section className="vl-page-head vl-process-head"><span className="vl-label">FROM WHAT IF → WHAT’S NEXT</span><h1>A little chemistry.<br/><em>A lot of clarity.</em></h1><p>Five connected chapters. Something concrete at the end of every one.</p></section><section className="vl-process-body"><aside><span className="vl-label">THE PROJECT, UNFOLDED</span><nav aria-label="Project chapters">{stages.map(([n,,name])=><a href={'#chapter-'+n} key={n}><span>{n}</span>{name}</a>)}</nav><Link className="vl-link" href="/contact">Start chapter one <span>↗</span></Link></aside><div>{stages.map(([n,title,name,copy,result,input])=><article className="vl-chapter" id={'chapter-'+n} key={n}><header><small>{name}</small><span>{n}</span></header><h2>{title}</h2><p>{copy}</p><div className="vl-chapter-result"><small>THE OUTCOME</small><strong>{result}</strong></div><details><summary>Your part in the process <span>+</span></summary><p>{input}</p></details></article>)}</div></section><section className="vl-process-end vl-pad"><h2>No disappearing acts.<br/>No mystery middle.</h2><p>Just visible decisions and a shared sense of where the project is going.</p><Link className="vl-button" href="/build">Give your idea a scope <span>↗</span></Link></section></main>}
